### ISSUE TITLE
Small objects effectively invisible in the UV window

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#14]
The model maker doesn't handle tiny objects (Below 1 point) very well. It seems impossible to scale the overall UV map, and it's very difficult to even see them, let alone move them around for texturing. Would it be possible for the model maker to sort of... "Smart scale" objects and try to place them around the UV map, instead of just using the 1:1 size?
My only recourse right now is to scale up their UV mapping, but it ends up looking weird when their texture has more detail than the rest.

**Comment by tyronx** [comment]
Fixed in the latest version through "UV Snap" toggle
