### ISSUE TITLE
Ctrl+Click selection too sensitive

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#16]
It's really finicky in the view menu, but the real problem is whenever I use the CTRL key with anything (Ctrl+shift click for fine tuned movement/scaling, Ctrl+Z, Ctrl+S....), it'll randomly select some part, and half the time it'll mess it up by inflating it.
It seems to happen most often when my mouse is over the selection box, but I can't reproduce it 100%

I would just drop the ctrl+click selection to be honest. I don't know about other people, but I never use it.

**Comment by tyronx** [comment]
Yea the Ctrl + Mouse Hover over center window thing bugged me also forever. I made it back to Ctrl + Mouse Click over the element to select again.
