### ISSUE TITLE
Add a texture tile function

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#18]
Currently, if I have, say, a 2x2 block object and I want it to use texture tiling, I need to split it into separate 1 block objects. There should be a way to tell an object to use texture tiling instead of having to fill out the entire texture

**Comment by tyronx** [comment]
Would need a very different texturing method in the engine i.e. array textures instead of using texture atlasses.

**Comment by Balduranne** [comment]
You already mentioned on discord, bummer
