### ISSUE TITLE
Feature Request: Wireframe mode, toggled object visibility

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#20]
I often need a size reference for some objects, so it would be nice to make my reference objects wireframe and/or invisible so I can see what I'm doing better.

**Comment by tyronx** [comment]
Added object visibility now. Is that very useful for you right now? Then I'll make another java8 release.

**Comment by Balduranne** [comment]
Very, yes!

**Comment by tyronx** [comment]
:P
