### ISSUE TITLE
Bug Model Editor - Undo

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#32]
Undo needs to do the action, not the individual steps. e.g. If you drag-rescale and object 3 steps, undo should undo the whole action, not one step at a time.

**Comment by tyronx** [comment]
What is drag-rescale?

**Comment by tenabraex** [comment]
when you resize an object in the model window rather than typing coords. this is mostly a problem because of the other issue where dragging around with the mouse sometimes just grabs a random object

**Comment by tyronx** [comment]
Drag-resizing does seem to undo the whole action for me, are you on the latest version?

**Comment by tyronx** [comment]
ow, it might be because i fixed an issue related to that. Let's see if the next version still has this bug for you

**Comment by tyronx** [comment]
no new info in a while, closing.
