### ISSUE TITLE
Feature Request (also a little bug): Model Editor - Export image sequence

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#40]
It would be cool if we could export an image sequence rather than a .gif, this is a lot friendlier for editing if we're trying to do a showreel of model anims.

An alternative would be exporting an .mp4

Im guessing the current export to gif is doing an image sequence then saving it as a gif since it likes to bug out between exports if you try to do multiple gifs without saving in between each one.

**Comment by tyronx** [comment]
How does it bug out?

**Comment by tenabraex** [comment]
I could swear I added a second comment to this... Turns out it wasn't bugging out, some of the anims were just large and took a while to compile in the background after the frames were generated. Since there's no progress bar and it keeps letting you work I assumed it was bugging out and not letting me export 2 sequences in a row.

**Comment by tenabraex** [comment]
Has been done.

**Comment by tenabraex** [comment]
Added
