### ISSUE TITLE
creating an element with negative size doesnt generate UVs correctly

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#49]
If you create geometry with a negative value (e.g. 2, 1, -10) the UVs for the negative face will only be 1 voxel wide in auto-UV.

e.g. the up/down UV is wrong here.

![Desktop Screenshot 2019 04 19 - 19 02 56 37](https://user-images.githubusercontent.com/47406324/56417083-2b455c00-62d6-11e9-9287-89be60945cb8.png)

**Comment by tyronx** [comment]
Should not be allowed to have negative sized elements to begin with. I'll disable that.
