### ISSUE TITLE
Custom / Negative UVs reset on focus change

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#50]
This one's been around since the last update but i've usually been able to work around it without too much hassle. When you assign custom UVs they like to reset themselves on save or on changing tab... i'd guess whenever VSMC is registering a state change. 

This is particularly bad when you make co-ordinates negative (e.g. when mirroring UVs on an object) In my current project it's happening whenever I try to remap this face.

As you can see also, all the UV controls move the UV negatice Y instead of the width/height controls expanding it (this is also a typical issue in the current version i've not bothered to mention till now)

- I thought maybe it relates to the non-uniform shape of the object, but no, even making it a cube does the same thing.
-Its also not related to texture rotation. 
- It doesn't matter which face, they will all halve in width like this.

The only way around it is to select another element (that doesn't have custom UV) before changing tab

https://youtu.be/F_M-ifWOm48

**Comment by tyronx** [comment]
fixed the reset on focus change but i don't understand your other issue. For starters I don't see any negative values in your videos and there are no width/height controls in the Face tab. The 4 values there are the Start and End Position of the UV coords.

**Comment by tenabraex** [comment]
Yeah i didnt demo negative values in that one.

Basically if you want to save texture space by putting say both ears, both hands, etc on the same spot, one of them will need to be reversed or it'll look wrong. In this case you'd have one set of positive UVs 
xy1 to xy2 and the other set would be negative xy2 to xy1

I think when I had you fix that rounding issue it made the modeller immune to negative values so you get the same issue as in the video.

I can make you a video of what im talking about if it helps

**Comment by tenabraex** [comment]
![reverse_uvs](https://user-images.githubusercontent.com/47406324/64078035-7c03a180-cd19-11e9-8902-87906d0e3840.PNG)

Here's what I mean by negative UVs... technically you're right there are no negative numbers, but its achieved by dragging co-ordinate 2 back over co-ordinate 1 so flipping (mirroring) them. Note that there are models in the core game this affects (some of the plant models I was playing with earlier for example have their UVs break if change focus while having them selected)

This is the biggest issue in the editor atm in my opinion.

I think it probably all relates to the bug where rescaling an entire heirachy often breaks the UVs.

**Comment by tenabraex** [comment]
This is fixed in the current builds. They dont reset themselves now.
