### ISSUE TITLE
Bug: Weird behaviour when trying to undo step parenting

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#52]
I already managed to break it! \o/

This occurs whenever I set the object to have a step parent and then attempt to undo anything. In this case moving it around.
![image](https://user-images.githubusercontent.com/10406037/65158061-bbabd800-d9ff-11e9-88d7-50ef2dbeb9e4.png)

**Comment by tyronx** [comment]
ok fixed for next release

**Comment by Balduranne** [comment]
Problem persists when removing objects 
![image](https://user-images.githubusercontent.com/10406037/65451723-c30f1f00-de0d-11e9-8906-2c77a2e1c4bc.png)

**Comment by tyronx** [comment]
ok should hopefully be fixed too
