### ISSUE TITLE
Feature Request: Moving UV faces individiually in Entity Texturing mode

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#54]
My biggest pet peeve with optimizing a UV map is not being to move an individual face without moving the entire object around. Could you add a toggleable way to move just one face around in the UV screen while seeing the rest? I know I can switch to regular texturing mode, but then I don't see where all the other faces are in relation to it.

**Comment by tyronx** [comment]
if you disable auto-uv you can do that, no?

**Comment by Balduranne** [comment]
> 
> 
> if you disable auto-unwrap you can do that, no?
I... Oh. I'm a dumbass
