### ISSUE TITLE
Bug: Can export UV Map that ISN'T a multiply of 8, but cannot IMPORT textures

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#55]
I can do this and export a 9x9 scaled up UV map, but then the program won't let me load the texture because it's not a multiply of 8.
![image](https://user-images.githubusercontent.com/10406037/65160900-9d94a680-da04-11e9-8d93-b27cda9a093c.png)

**Comment by tyronx** [comment]
ok, now displays an error if one tries to supply a non-multiple-8 values
