### ISSUE TITLE
Bug: Step-parented objects persists after creating a new file

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#58]
![image](https://user-images.githubusercontent.com/10406037/65460381-bc89a300-de1f-11e9-95a8-905d2fc284d3.png)
It only goes away if I clear the backdrop. It seems that the step-parenting makes the program stick to the parent object instead of the one you're actually making

**Comment by tyronx** [comment]
thanks, fixed for next release
