### ISSUE TITLE
Copied item UVs start at top left, rather than being in same position as copied item UVs

### ISSUE THREAD

**Issue by brummbar7** [anegostudios/vsmodelcreator#61]
As the title says.  If you copy an items (or maybe it's a group) The UVs of the new set of items are not mapped the same as those of the items you copied.  So you have to reposition them.   The UV positions should be copied too.

**Comment by tenabraex** [comment]
Yeah this is an odd one, some things DO replicate their UVs and some things dont, I think it's something to do with auto-modes... often I find if ive manually edited UVs it will keep them when duplicated.

For the most part I dont mind the behaviour as ill often want to mirror a UV on a duplicated object and having them appear in the top left means I dont have to fight the Z-order of the UVs to move the one I want.

I leave the top-left clear of UVs for a few pixels for this purpose

**Comment by tyronx** [comment]
thanks, this is now fixed
