### ISSUE TITLE
Set animation key with current rotation / display current rotation

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#62]
When you make a new animation key in VSMC it will reset rotation/postion. This is fine most of the time, but it makes it very difficult to do complex looping animations without some serious guesstimation.

I would like a 'set key at current position/rotation option, even if it's a modifier function rather than its own button.

Failing that, if we could at least have the rotation/position constantly update even when there's no key on that frame so we can manually note them and recreate them.

**Comment by tyronx** [comment]
This is now added by holding the shift key while pressing the position/rotation/stretch enable buttons, will be in the next version
