### ISSUE TITLE
texture load issue in entity mode with multiple textures

### ISSUE THREAD

**Issue by tenabraex** [anegostudios/vsmodelcreator#63]
If you have multiple textures in entity texture mode on reload the editor will assign the first texture to all objects (and act as though that's where the UVs lie)

If you manually reassign all textures it will work fine until you reload at which time it will reset again.

This does NOT affect the actual file, all texture references/texture codes in the file are correct, it's only the editor that is displaying the incorrect texture.

This only happens when you close VSMC, if you reload without closing the client it will work properly.

**Comment by tenabraex** [comment]
Hmn... the bit about only happening if you dont close VSMC isn't consistent... I think if you have multiple stuff with different textures (so in my case i have claws and staff on the model which is 3 different heirarchies but all use the same texture) the staff keeps resetting.

**Comment by tyronx** [comment]
this should now be addressed properly
