### ISSUE TITLE
Cant find file : vsmodelcreator.jar

### ISSUE THREAD

**Issue by JRL101** [anegostudios/vsmodelcreator#72]
![image](https://user-images.githubusercontent.com/33255536/107027005-81a2c800-67e6-11eb-91d7-3f0fded3edc4.png)
from what i can tell its not building the file because of this line defining a user name that doesnt exsist on other peoples computers. But im unsure.
I just tracked it down from this file name 
![image](https://user-images.githubusercontent.com/33255536/107027152-b31b9380-67e6-11eb-8cab-05efa6f2685e.png)
i cant find that jar file in any where in the creators folder.

**Comment by tyronx** [comment]
you're trying to build the .jar from scratch? I do that through 'export' in eclipse, that should work

**Comment by JRL101** [comment]
So very sorry, i found the other installer, through the wiki, only reason i went through to this one was it was linked to me instead of the correct location. But got it working, all good, im an idiot :D

**Comment by tyronx** [comment]
hehe no problem
