### ISSUE TITLE
Feature Request: Make the center lines thicker 

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/vsmodelcreator#78]

**Comment by tyronx** [comment]
which center lines?

**Comment by Balduranne** [comment]
Sorry; The center lines in the grid. I often use it for reference to make sure the object is centered enough 
![image](https://user-images.githubusercontent.com/10406037/119657306-bb312a80-bdf9-11eb-9ad3-4a92c5d7464f.png)

**Comment by tyronx** [comment]
ok, added this, will be in the next release
