### ISSUE TITLE
Can't build or run on linux

### ISSUE THREAD

**Issue by Arsakes** [anegostudios/vsmodelcreator#93]
I couldn't build the thing on linux some instructions in readme would be nice.

The builded version in zip doesn't work on linux (should it?)
I can run it, but when I try to open a file I'm getting following error:

```
    java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
    no swt-win32-4629 in java.library.path
    no swt-win32 in java.library.path
    Can't load library: /home/pietrko/.swt/lib/linux/x86_64/libswt-win32-4629.so
    Can't load library: /home/pietrko/.swt/lib/linux/x86_64/libswt-win32
```

**Comment by kane-thornwyrd** [comment]
Sorry tyronx, but… 
![Screenshot_20221201_081344](https://user-images.githubusercontent.com/625236/204989251-4f6a0e2e-ee85-4f4b-86ac-110fc063c69c.png)

**Comment by kane-thornwyrd** [comment]
I will clone the repos and try to launch from sources

**Comment by tyronx** [comment]
Could you try copying the natives/linux/swt-gtk4.jar to vsmodelcreator_lib/swt.jar and see if that fixes it?

**Comment by kane-thornwyrd** [comment]
[rant toward java start]
So… I got from error to error, at some point I even had to add the "--illegal-access=warn" to the java invokation… And I managed to understand that it require Java 11… I feel stupid… And my critics on how java handle the jars is increasing… Wouldn't be that hard to add somewhere in the JVM that the jar it is trying to launch need X version of the JVM ? -_-' I mean, they say "it require the X version of the API" (version 55.0 at least in this case), but it is a totally different version than the JRE/JDK…
[rant end]

Thank you Tyron, it works perfectly, I just had to install the jdk11 package once (`$ yay -Suy jdk11`) , to get the error that it need for us to download "manually" the archive from the oracle site and for the cache folder to be created, then do:
```shell
$ cp ~/[my download folder]/jdk-11.0.15.1_linux-x64_bin.tar.gz ~/.cache/yay/jre11
$ cp ~/[my download folder]/jdk-11.0.15.1_linux-x64_bin.tar.gz ~/.cache/yay/jdk11
$ yay -Suy jdk11
$ cd ~/[my download folder]/vsmodelcreator_14nov2022
$ java -jar vsmodelcreator.jar
```
And everything works and it's beautiful, and it's great, and I love that I can now enter a new stage in my modding journey :) ! THANK YOU TYRON !

P.S. Future Kane, I know you'll end up here again, you need to work on your memory, but here's the solution at least for the version of nov 2022, apart that try not remember too much of this year tho, it was the Hell year, so be grateful to your dumb past self.

**Comment by tyronx** [comment]
Wow, strange, and on Windows it only runs under Java 8
