### ISSUE TITLE
'Global' tree unique names

### ISSUE THREAD

**Issue by danger-dan** [anegostudios/vsmodelcreator#98]
I ran into an issue a while back where I couldn't name elements with the same name across the elment tree. I modified the source so it would let me do just that and only force uniqueness for elements belonging to the same parent. In my specific case it was a requirement however I also wonder if maybe this should be default behaviour? 

If you want me to open a PR for this I'll do that. Otherwise feel free to close this issue if you think this is not important. I am happy enough keeping my copy going while I need it and rebasing every now and then.

**Comment by tyronx** [comment]
we need unique element names so we can search for them easily when loading the model in the engine
